version: "2"
volumes:
  data:
services:
  node-manager:
    build: ./node-manager
    volumes:
      - "data:/data"
    restart: always
    privileged: true
    network_mode: host
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.dbus: "1"
